apiVersion: batch/v1
kind: CronJob
metadata:
  name: rq-autoscaler
  namespace: default
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            kubectl.kubernetes.io/default-container: app
        spec:
          containers:
          - name: app
            image: ghcr.io/cpressland/rq-autoscaler:latest
            env: []
            imagePullPolicy: Always
            command:
            - rq-autoscaler
          restartPolicy: Never
          serviceAccountName: rq-autoscaler
