---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rq-autoscaler
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rq-autoscaler
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rq-autoscaler
subjects:
- kind: ServiceAccount
  name: rq-autoscaler
  namespace: default
